# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBVvbMdLC8f3Elj13kTlsRdA6L4dyl2M
"""

def add(a,b):
  return a+b

def get_primes():
  num = 2
  while True:
    if is_prime(num):
      yield num
    num += 1

from itertools import product
a={1, 2}
print((list(product(range(3), a))))

count=0
for i in range(1,5):
  while num>1:
    print(i)
    print('prime: ')
    for i in range(1,10):
      print()