# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBVvbMdLC8f3Elj13kTlsRdA6L4dyl2M
"""

def add(a,b):
  return a+b